#!/usr/bin/env python

import os, sys
import findrox; findrox.version(2, 0, 0)
import rox

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

import manage

try:
    manage.show(sys.argv[1:])
    rox.mainloop()
except:
    rox.report_exception()
