#!/usr/bin/env python

import os, sys
import time

argv0=sys.argv[0]
app_dir=os.path.dirname(argv0)

mp3_dir=os.path.join(app_dir, 'mp3')
mp3_files=os.listdir(mp3_dir)
mp3_files.sort()

paths=[]
for mp3 in mp3_files:
    if mp3[-4:]=='.mp3':
        paths.append(os.path.join(mp3_dir, mp3))

os.system('xmms "%s" &' % paths[0])
time.sleep(3) # Allow it time to start up
for path in paths[1:]:
    os.system('xmms -e "%s"' % path)
