#!/usr/bin/env python

import os, sys
import time

import findrox; findrox.version(2, 0, 0)
import rox, rox.choices

rox.setup_app_options('Album')
music_box=rox.options.Option('use_music_box', True)
rox.app_options.notify()

types=('.mp3', '.ogg')

argv0=sys.argv[0]
app_dir=os.path.dirname(argv0)

audio_dir=os.path.join(app_dir, 'audio')
if not os.path.isdir(audio_dir):
    audio_dir=os.path.join(app_dir, 'mp3')
if not os.path.isdir(audio_dir):
    audio_dir=app_dir
audio_files=os.listdir(audio_dir)
audio_files.sort()

paths=[]
for audio in audio_files:
    if audio[-4:]in types:
        paths.append(os.path.join(audio_dir, audio))

def send_xmms(p):
    os.system('xmms "%s" &' % p[0])
    time.sleep(3) # Allow it time to start up
    for path in p[1:]:
        os.system('xmms -e "%s"' % path)

def send_music_box(p):
    loc=None
    appdir=os.getenv("APPDIRPATH",
                     "%s/Apps:/usr/local/apps:/usr/apps" % os.getenv("HOME"))
    for dir in appdir.split(':'):
        run=os.path.join(dir, 'MusicBox', 'AppRun')
        if os.access(run, os.X_OK):
            loc=run
            break
    print loc
    if not loc:
        appdir=os.getenv("PATH")
        for dir in appdir.split(':'):
            run=os.path.join(dir, 'MusicBox', 'AppRun')
            if os.access(run, os.X_OK):
                loc=run
                break
    print loc
    if not loc:
        return False

    cmd=loc
    for f in p:
        cmd+=' "%s"' % f
    print >>sys.stderr, cmd
    os.system(cmd)
    return True
    
if music_box.int_value:
    if not send_music_box(paths):
        send_xmms(paths)
else:
    send_xmms(paths)
