#!/usr/bin/env python

import os, sys
import time

types=('.mp3', '.ogg')

argv0=sys.argv[0]
app_dir=os.path.dirname(argv0)

audio_dir=os.path.join(app_dir, 'audio')
audio_files=os.listdir(audio_dir)
audio_files.sort()

paths=[]
for audio in audio_files:
    if audio[-4:]in types:
        paths.append(os.path.join(audio_dir, audio))

os.system('xmms "%s" &' % paths[0])
time.sleep(3) # Allow it time to start up
for path in paths[1:]:
    os.system('xmms -e "%s"' % path)
