#!/bin/sh

PROG=Clock

APP_DIR=`dirname "$0"`
APP_DIR=`cd "$APP_DIR";pwd`; export APP_DIR

if [ "x$PLATFORM" = x ]; then
  ARCH=`uname -m`
  case $ARCH in
	i?86) ARCH=ix86 ;;
  esac

  PLATFORM=`uname -s`-$ARCH export PLATFORM
fi

if [ ! -x "$APP_DIR/AppletRun" ]; then
  (cd "$APP_DIR" ; ln -s AppRun AppletRun)
fi

if [ "x$MAKE" = x ]; then
  MAKE=make export MAKE
fi

ROX_CLIB=`"$APP_DIR/libdir" --0install www.kerofin.demon.co.uk ROX-CLib`/AppRun
if [ -z "$LD_LIBRARY_PATH" ]; then
    LD_LIBRARY_PATH=`"$ROX_CLIB" --runtime`
else
    LD_LIBRARY_PATH=`"$ROX_CLIB" --runtime`:$LD_LIBRARY_PATH
fi
export LD_LIBRARY_PATH

DEBUGGER=""

build_failed()
{
	echo Build failed >&2
	echo Press Return... >&2
	read WAIT
	exit 1
}

case $1 in
    --debug) shift ; DEBUGGER=gdb ;;
    --compile)
	if [ ! -d "$APP_DIR/src" ] ; then
	    echo "ERROR from $0:" >&2
	    echo "Cannot compile - source code is missing!" >&2
	    exit 1
	fi
	echo "Configuring $APP_DIR... please wait..." >&2
	mkdir -p "$APP_DIR/$PLATFORM"
	mkdir -p "$APP_DIR/$PLATFORM-build"
	cmake \
	    -DCMAKE_INSTALL_PREFIX:PATH="$APP_DIR/$PLATFORM" \
	    -S "$APP_DIR/src" \
	    -B "$APP_DIR/$PLATFORM-build" || build_failed
	cd "$APP_DIR/$PLATFORM-build"
	make install || build_failed
	exit 0

esac

BIN="$APP_DIR/$PLATFORM/bin/$PROG"

if [ -x "$BIN" ] ; then
    exec $DEBUGGER "$BIN" "$@"
else
    echo "ERROR from $0:" >&2
    echo "I cannot find an executable file for your host type ($PLATFORM)." >&2
    #echo "Try using the --compile option." >&2
    echo "Trying to compile..." >&2
    if [ -n "$DISPLAY" ]; then
	xterm -e "$0" --compile
    else
	"$0" --compile
    fi
    if [ -x "$BIN" ]; then
	exec "$BIN" "$@"
    fi
    exit 1
fi
