#!/bin/sh

echo Extracting messages from source files...
echo

(cd ../; pygettext AppRun uri_handler.py)

echo
echo Updating all .po files...
echo

for FILE in *.po; do
	echo -n "Updating '$FILE' translation"
	mv $FILE $FILE.old
	msgmerge $FILE.old ../messages.pot > $FILE
done
