#!/usr/bin/env python

import os, sys

import findrox; findrox.version(2, 0, 3)
import rox, rox.options, rox.filer

import urlparse

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

import options

valid_schemes=('smb', 'cifs')

def check_files():
    dev=options.getFuseDevice()
    if dev and not os.access(dev, os.F_OK):
        rox.alert(_('Device "%s" not found, fuse not running') % dev)
        return False

    cmd=options.getFusesmbCommand()
    if not os.path.isabs(cmd) and not in_path(cmd):
        rox.alert(_('fusesmb command not found, cannot continue'))
        return False
    elif os.path.isabs(cmd) and not os.access(cmd, os.X_OK):
        rox.alert(_('fusesmb command "%s" not executable, cannot continue') %
                  cmd)
        return False

    cmd=options.getSmbclientCommand()
    if not os.path.isabs(cmd) and not in_path(cmd):
        rox.alert(_('smbclient command not found, cannot continue'))
        return False
    elif os.path.isabs(cmd) and not os.access(cmd, os.X_OK):
        rox.alert(_('smbclient command "%s" not executable, cannot continue') %
                  cmd)
        return False

    mnt=options.getMountPoint()
    if os.access(mnt, os.F_OK):
        if not os.path.isdir(mnt):
            rox.alert(_('"%s" is not a directory, cannot use as a mount point')%
                      mnt)
            return False

    else:
        try:
            os.makedirs(mnt)
        except OSError, ex:
            rox.alert(_('Failed to create "%s" as a mount point: %s') % (mnt,
                                                                         ex))
            return False

    return True

def in_path(cmd):
    #print cmd
    for d in os.getenv('PATH').split(':'):
        f=os.path.join(d, cmd)
        #print f
        if os.access(f, os.X_OK):
            return f
    #print 'not found'

def ensure_mounted(mnt=None):
    if not mnt:
        mnt=options.getMountPoint()
    if not os.path.ismount(mnt):
        try:
            cmd=options.getFusesmbCommand()
            ret=os.spawnlp(os.P_WAIT, cmd, 'fusesmb', mnt)
        except:
            rox.report_exception()
            return False

        return ret==0

    return True

def unmount(mnt=None):
    if not mnt:
        mnt=options.getMountPoint()
    cin, cout, cerr=os.popen3('%s -u %s' % (options.getFusermountComamnd(),
                                            mnt))
    errmsg=''.join(cerr.readlines())

    if errmsg:
        rox.alert(_('Unmounting "%s":\n%s') % (mnt, errmsg))
        return False

    return True
    
def parse_uri(uri):
    parts=urlparse.urlsplit(uri)
    #print parts

    if parts[0] not in valid_schemes:
        return None, None

    if parts[2].startswith('//'):
        if '/' in parts[2][2:]:
            netloc, path=parts[2][2:].split('/', 1)

        else:
            netloc=parts[2][2:]
            path=''

    else:
        netloc=parts[1]
        path=parts[2]

    return netloc.upper(), path

def open_uri(uri):
    netloc, path=parse_uri(uri)
    #print netloc, path
    if netloc is None:
        return

    mnt=options.getMountPoint()
    if not ensure_mounted(mnt):
        return

    if not netloc:
        rox.filer.open_dir(mnt)
        return

    if os.path.isdir(os.path.join(mnt, netloc)):
        if path and path!='/':
            opath=os.path.join(mnt, netloc, path)
        else:
            opath=os.path.join(mnt, netloc)

        rox.filer.open_dir(opath)

    else:
        domain=lookup_domain(netloc)
        
        if path and path!='/':
            opath=os.path.join(mnt, domaim, netloc, path)
        else:
            opath=os.path.join(mnt, domain, netloc)

        rox.filer.open_dir(opath)

def lookup_domain(host):
    cin, cout, cerr=os.popen3('smbclient -NL %s' % host)
    for l in cerr:
        #print l
        if l.startswith('Domain=['):
            words=l.split()
            #print words
            s=words[0].find('[')
            e=words[0].find(']')

            return words[0][s+1:e]
            
    return options.getDomain()

def options_updated():
    pass

options.addNotify(options_updated)

if __name__=='__main__':

    if len(sys.argv)>1:
        if sys.argv[1]=='--options':
            options.show()

        elif sys.argv[1]=='--unmount':
            unmount()

        else:
            check_files()
            for a in sys.argv[1:]:
                open_uri(a)

    else:
        check_files()
        open_uri('smb://')
