#!/usr/bin/env python

from sys import argv, exit
from os.path import dirname

from gtk import *
from GDK import *

from SplitF import *

app_dir = dirname(argv[0])

if len(argv) != 2:
	report_error("Drag a file SplitF to split it. " +
			"Drag a split part onto it to join.")
	exit();
else:
	make_splitter(argv[1])

mainloop()
