#!/usr/bin/env python
#
# $Id: AppRun,v 1.6 2004/06/21 20:59:59 stephen Exp $

import os, sys
import time

import findrox; findrox.version(1, 9, 14)
import rox, rox.choices, rox.options
import gobject

import urllib, urlparse

import xml.dom, xml.dom.minidom

_=rox._

rox.setup_app_options('Fetch')

allow_pw_change=rox.options.Option('allow_pw_change', True)
wait_for=rox.options.Option('wait_for', 3)

rox.app_options.notify()

def run_main():
    while rox.g.events_pending():
        rox.g.main_iteration()

def get_filename(url):
    scheme, location, path, query, fragment=urlparse.urlsplit(url)
    base=os.path.basename(path)
    if not base:
        base='index.html'
    fname=base
    num=1
    while os.access(fname, os.F_OK):
        dot=base.index('.')
        if dot>=0:
            fname=base[:dot]+('-%d' % num)+base[dot:]
        else:
            fname=base+'-%d' % num
        
        num+=1
        
    return fname

class ROXURLopener(urllib.FancyURLopener):
    def prompt_user_passwd(self, host, realm):
        #print host
        #print realm
        try:
            pwds=get_passwords()
            if pwds.has_key((host, realm)):
                user, password=pwds[host, realm]
            else:
                user=None
                password=None

            if user and password and not allow_pw_change.int_value:
                return user, password
            ouser=user
            opass=password
            pd=PasswordWindow(host, realm, user, password)
            res=pd.run()
            if res==rox.g.RESPONSE_OK:
                user, password=pd.get_login()
                #print user, password
                if pd.get_save() and (user!=ouser or password!=opass):
                    add_password(pwds, host, realm, user, password)
                return user, password
        except:
            rox.report_exception()
        return None, None
    
    # Changed from urllib.FancyURLopener to pass extra arg
    def retrieve(self, url, filename=None, reporthook=None, data=None):
        """retrieve(url) returns (filename, None) for a local object
        or (tempfilename, headers) for a remote object."""
        url = urllib.unwrap(urllib.toBytes(url))
        if self.tempcache and self.tempcache.has_key(url):
            return self.tempcache[url]
        type, url1 = urllib.splittype(url)
        if not filename and (not type or type == 'file'):
            try:
                fp = self.open_local_file(url1)
                hdrs = fp.info()
                del fp
                return urllib.url2pathname(urllib.splithost(url1)[1]), hdrs
            except IOError, msg:
                pass
        fp = self.open(url, data)
        headers = fp.info()
        if not filename:
            import tempfile
            garbage, path = urllib.splittype(url)
            garbage, path = urllib.splithost(path or "")
            path, garbage = urllib.splitquery(path or "")
            path, garbage = urllib.splitattr(path or "")
            suffix = os.path.splitext(path)[1]
            filename = tempfile.mktemp(suffix)
            self.__tempfiles.append(filename)
        result = filename, headers
        if self.tempcache is not None:
            self.tempcache[url] = result
        tfp = open(filename, 'wb')
        bs = 1024*8
        size = -1
        blocknum = 1
        if reporthook:
            if headers.has_key("content-length"):
                size = int(headers["Content-Length"])
            reporthook(0, bs, size, headers)
        block = fp.read(bs)
        if reporthook:
            reporthook(1, bs, size)
        while block:
            tfp.write(block)
            block = fp.read(bs)
            blocknum = blocknum + 1
            if reporthook:
                reporthook(blocknum, bs, size)
        fp.close()
        tfp.close()
        del fp
        del tfp
        return result


class FetchWindow(rox.Dialog):
    def __init__(self, url, target=None):
        self.url=url
        if not target:
            target=get_filename(url)
        self.target=target
        self.start_time=None
        
        rox.Dialog.__init__(self)
        self.set_title(self.url)
        self.add_button(rox.g.STOCK_CANCEL, rox.g.RESPONSE_CANCEL)
        self.connect('response', self.do_response)

        vbox=self.vbox

        table=rox.g.Table(8, 2)
        vbox.pack_start(table, padding=4)

        line=0
        l=rox.g.Label(_('<b>Source</b>'))
        l.set_use_markup(True)
        l.set_alignment(1., 0.5)
        table.attach(l, 0, 1, line, line+1, xpadding=2)
        l=rox.g.Label(self.url)
        l.set_line_wrap(True)
        l.set_alignment(0., 0.5)
        table.attach(l, 1, 2, line, line+1, xpadding=2)

        line+=1
        l=rox.g.Label(_('<b>Size</b>'))
        l.set_use_markup(True)
        l.set_alignment(1., 0.5)
        table.attach(l, 0, 1, line, line+1, xpadding=2)
        l=rox.g.Label('')
        l.set_alignment(0., 0.5)
        table.attach(l, 1, 2, line, line+1, xpadding=2)
        self.size_l=l

        line+=1
        l=rox.g.Label(_('<b>Type</b>'))
        l.set_use_markup(True)
        l.set_alignment(1., 0.5)
        table.attach(l, 0, 1, line, line+1, xpadding=2)
        l=rox.g.Label('')
        l.set_alignment(0., 0.5)
        table.attach(l, 1, 2, line, line+1, xpadding=2)
        self.type_l=l

        line+=1
        l=rox.g.Label(_('<b>Download to</b>'))
        l.set_use_markup(True)
        l.set_alignment(1., 0.5)
        table.attach(l, 0, 1, line, line+1, xpadding=2)
        l=rox.g.Label(os.getcwd())
        l.set_alignment(0., 0.5)
        table.attach(l, 1, 2, line, line+1, xpadding=2)
        line+=1
        l=rox.g.Label(self.target)
        l.set_alignment(0., 0.5)
        table.attach(l, 1, 2, line, line+1, xpadding=2)

        line+=1
        self.msg1=rox.g.Label('')
        self.msg1.set_line_wrap(True)
        table.attach(self.msg1, 0, 2, line, line+1)

        line+=1
        self.prog=rox.g.ProgressBar()
        table.attach(self.prog, 0, 2, line, line+1)

        line+=1
        l=rox.g.Label(_('<b>Estimated time</b>'))
        l.set_use_markup(True)
        l.set_alignment(1., 0.5)
        table.attach(l, 0, 1, line, line+1, xpadding=2)
        l=rox.g.Label('')
        l.set_alignment(0., 0.5)
        table.attach(l, 1, 2, line, line+1, xpadding=2)
        self.etime=l

        self.connect('delete_event', self.delete_event)

        self.show_all()
        self.opener=ROXURLopener()
        self.open_server()

    def do_response(self, *unused):
        sys.exit(0)

    def delete_event(self, *unused):
        #print 'delete_event', self, unused
        #print rox._toplevel_windows
        self.close()
        #print rox._toplevel_windows
        
    def message(self, text):
        self.msg1.set_text(text)

    def percent_done(self, size, total):
        if self.prog is None:
            return
        if size>total:
            val=1.
        elif total>0:
            val=float(size)/total
        else:
            self.active()
            return
        self.prog.set_fraction(val)
        self.prog.set_text('%d%%' % (val*100))
        self.set_title('%d%% %s' % (val*100, self.target))

        if self.start_time and total>0 and size>0:
            now=time.time()
            elapsed=now-self.start_time
            etotal=elapsed*total/size
            eleft=etotal-elapsed
            #print elapsed, etotal, eleft
            secs=int(eleft)
            hours=int(secs/3600)
            secs-=hours*3600
            mins=int(secs/60)
            secs-=mins*60
            if eleft<=0:
                tstr=_('Done')
            elif hours>0:
                tstr='%d:%02d:%02d' % (hours, mins, secs)
            else:
                tstr='%02d:%02d' % (mins, secs)
            self.etime.set_text(tstr)
            
        run_main()

    def active(self):
        self.prog.set_text('')
        self.prog.pulse()
        run_main()

    def close(self):
        #print 'close'
        self.hide()
        self.destroy()
        self.prog=None
        rox.g.main_quit()

    def open_server(self):
        self.message(_('Downloading'))
        self.start_time=time.time()
        fname, message=self.opener.retrieve(self.url, self.target, self.report)
        #print message
        #print dir(message)
        self.finished(message)

    def report(self, nblock, bsize, tsize, headers=None):
        #print 'report', self, nblock, bsize, tsize
        if headers and headers.has_key('Content-Type'):
            self.type_l.set_text(headers['Content-Type'])
        nb=nblock*bsize
        if tsize>0:
            self.percent_done(nb, tsize)
            self.size_l.set_text('%d bytes' % tsize)
        else:
            self.active()
        run_main()

    def finished(self, header):
        if header.has_key('Content-Type'):
            self.type_l.set_text(header['Content-Type'])
        self.message('Done')
        rox.g.timeout_add(wait_for.int_value*1000, self.close)
        rox.g.main()
        
class PasswordWindow(rox.Dialog):
    def __init__(self, host, realm, user=None, password=None):
        self.host=host
        self.realm=realm
        
        rox.Dialog.__init__(self)
        self.set_title(_('Password for %s' % host))
        self.add_button(rox.g.STOCK_CANCEL, rox.g.RESPONSE_CANCEL)
        self.add_button(rox.g.STOCK_OK, rox.g.RESPONSE_OK)
        self.connect('response', self.do_response)

        vbox=self.vbox

        table=rox.g.Table(4, 2)
        vbox.pack_start(table, padding=4)
        line=0
        
        l=rox.g.Label(_('Enter username and password for %s at %s') %
                      (realm, host))
        l.set_line_wrap(True)
        l.set_alignment(0., 0.5)
        table.attach(l, 0, 2, line, line+1, xpadding=2)

        line+=1
        l=rox.g.Label(_('<b>Username</b>'))
        l.set_use_markup(True)
        l.set_alignment(1., 0.5)
        table.attach(l, 0, 1, line, line+1, xpadding=2)
        self.user=rox.g.Entry(0)
        if user:
            self.user.set_text(user)
        table.attach(self.user, 1, 2, line, line+1, xpadding=2)

        line+=1
        l=rox.g.Label(_('<b>Password</b>'))
        l.set_use_markup(True)
        l.set_alignment(1., 0.5)
        table.attach(l, 0, 1, line, line+1, xpadding=2)
        self.password=rox.g.Entry(0)
        self.password.set_visibility(False)
        if password:
            self.password.set_text(password)
        table.attach(self.password, 1, 2, line, line+1, xpadding=2)

        line+=1
        self.can_save=rox.g.CheckButton(_('Remember for next time'))
        self.can_save.set_active(True)
        table.attach(self.can_save, 0, 2, line, line+1, xpadding=2)

        vbox.show_all()

    def do_response(self, *unused):
        self.hide()

    def get_login(self):
        return self.user.get_text(), self.password.get_text()

    def get_save(self):
        return self.can_save.get_active()

def _data(node):
	"""Return all the text directly inside this DOM Node."""
	return ''.join([text.nodeValue for text in node.childNodes
			if text.nodeType == xml.dom.Node.TEXT_NODE])

def get_passwords():
    fname=rox.choices.load('Fetch', 'passwords.xml')
    if not fname:
        return {}

    pwds={}
    doc=xml.dom.minidom.parse(fname)
    #print doc.getElementsByTagName('Entry')
    for entry in doc.getElementsByTagName('Entry'):
        host=entry.getAttribute('host')
        realm=entry.getAttribute('realm')

        node=entry.getElementsByTagName('User')[0]
        user=_data(node)
        node=entry.getElementsByTagName('Password')[0]
        password=_data(node)

        pwds[host, realm]=(user, password)

    return pwds

def save_passwords(pwds):
    fname=rox.choices.save('Fetch', 'passwords.xml')

    doc=xml.dom.minidom.Document()
    root=doc.createElement('Passwords')
    doc.appendChild(root)

    for key, value in pwds.iteritems():
        host, realm=key
        user, password=value

        node=doc.createElement('Entry')
        node.setAttribute('host', host)
        node.setAttribute('realm', realm)
        
        snode=doc.createElement('User')
        snode.appendChild(doc.createTextNode(user))
        node.appendChild(snode)
        snode=doc.createElement('Password')
        snode.appendChild(doc.createTextNode(password))
        node.appendChild(snode)
        
        root.appendChild(node)

    f=file(fname+'.tmp', 'w')
    doc.writexml(f)
    f.close()
    os.chmod(fname+'.tmp', 0600)
    os.rename(fname+'.tmp', fname)
        
def add_password(pwds, host, realm, user, password):
    pwds[host, realm]=(user, password)
    save_passwords(pwds)

def main():
    if len(sys.argv)>1:
        url=sys.argv[1]
        local=None
        if len(sys.argv)>2:
            local=sys.argv[2]
        try:
            win=FetchWindow(url, local)
            #rox.g.timeout_add(2*1000, win.update)
            #rox.g.main()
        except:
            rox.report_exception()
    else:
         rox.edit_options()
         rox.mainloop()

if __name__=='__main__':
    main()
