#!/bin/sh

echo Extracting messages from source files...
echo

(cd ..; if [ -f Makefile ] ; then make messages.pot; else python po/extopts.py ; xgettext --keyword=_ --keyword=N_ --output=messages.pot *.c Options_strings; fi )

echo
echo Updating all .po files...
echo

for FILE in *.po; do
	if [ -e $FILE ] ; then
		echo -n "Updating '$FILE' translation"
		mv "$FILE" "$FILE.old"
		msgmerge "$FILE.old" ../messages.pot > "$FILE";
		rm "$FILE.old"
	fi
done
