#!/bin/sh

echo Extracting messages from source files...
echo

(cd ..; make messages.pot)

echo
echo Updating all .po files...
echo

for FILE in *.po; do
	if [ -e $FILE ] ; then
		echo -n "Updating '$FILE' translation"
		mv "$FILE" "$FILE.old"
		msgmerge "$FILE.old" ../messages.pot > "$FILE";
		rm "$FILE.old"
	fi
done
