#!/usr/bin/env perl

chdir "../..";

system "cvs rel SystemTray";

open(VER, "SystemTray/AppRun --version 2>&1 |") or die "open(): $!";
while (<VER>) {
  last if /^SystemTray/;
}
close(VER);

/(\d+)\.(\d+)/;

($a, $b) = ($1, $2);

print "Version $a.$b --- OK?\n";

<STDIN> =~ /^[yY]/ or die "OK, fix the version number!\n";

system "cvs tag -F Release-$a-$b";
system "cd SystemTray/src/po; ./update-po; ./dist";

chdir;

mkdir "SystemTray-$a.$b", 0775 or warn "mkdir() failed: $!\n";
chdir "SystemTray-$a.$b";

system "cvs -d ~/projects/cvsroot export -r Release-$a-$b SystemTray";

system "cd SystemTray/src; aclocal; autoconf";
system "cp -r ~/projects/SystemTray/Messages/*.gmo SystemTray/Messages";

system "rm -r SystemTray/src/test SystemTray/src/autom4te.cache";

system "find -name '.cvsignore' | xargs rm";

system "tar czf ~/SystemTray-$a.$b.tgz SystemTray";
chdir "..";
system "rm -r SystemTray-$a.$b";

print "OK, done\n";
