#!/usr/bin/env python
#
# $Id: AppRun,v 1.1 2003/10/31 16:46:02 stephen Exp $

"""Manage the video thumbnail program"""

import findrox; findrox.version(1, 9, 13)
import rox

import sys
import vidthumb

# Are we to generate a thumb?
if len(sys.argv)>3:
    try:
        vidthumb.main(sys.argv[1:])
    except:
        t, m=sys.exc_info()[:2]
        print >> sys.stderr, '%s: %s %s' % (sys.argv[0], t, m)
        sys.exit(1)
    sys.exit(0)

# We are being run in configure mode
vidthumb.configure()
