#

CC=gcc
DEBUG=-g
CFLAGS=$(DEBUG) `gtk-config --cflags`
LIBS=`gtk-config --libs`
BINDIR=.

all: $(BINDIR)/free

$(BINDIR)/free: free.o choices.o
	$(LINK.c) -o $@ free.o choices.o $(LIBS)

clean:
	$(RM) *.o

depend: free.c choices.c
	makedepend `gtk-config --cflags` free.c choices.c

# DO NOT DELETE

free.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
free.o: /usr/include/sys/isa_defs.h /usr/include/sys/va_list.h
free.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
free.o: /usr/include/stdlib.h /usr/include/string.h /usr/include/stdarg.h
free.o: /usr/include/errno.h /usr/include/sys/errno.h /usr/include/fcntl.h
free.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
free.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
free.o: /usr/include/sys/time.h /usr/include/sys/time.h
free.o: /usr/include/sys/fcntl.h /usr/include/sys/mnttab.h
free.o: /usr/include/sys/statvfs.h /usr/local/include/gtk/gtk.h
free.o: /usr/local/include/gdk/gdk.h /usr/local/include/gdk/gdktypes.h
free.o: /usr/local/include/glib.h /usr/local/lib/glib/include/glibconfig.h
free.o: /usr/include/limits.h /usr/include/float.h
free.o: /usr/local/include/gdk/gdkcursors.h /usr/local/include/gdk/gdkrgb.h
free.o: /usr/local/include/gtk/gtkaccelgroup.h
free.o: /usr/local/include/gtk/gtkobject.h /usr/local/include/gtk/gtkarg.h
free.o: /usr/local/include/gtk/gtktypeutils.h
free.o: /usr/local/include/gtk/gtktypebuiltins.h
free.o: /usr/local/include/gtk/gtkenums.h /usr/local/include/gtk/gtkdebug.h
free.o: /usr/local/include/gtk/gtkaccellabel.h
free.o: /usr/local/include/gtk/gtklabel.h /usr/local/include/gtk/gtkmisc.h
free.o: /usr/local/include/gtk/gtkwidget.h
free.o: /usr/local/include/gtk/gtkadjustment.h
free.o: /usr/local/include/gtk/gtkdata.h /usr/local/include/gtk/gtkstyle.h
free.o: /usr/local/include/gtk/gtkalignment.h /usr/local/include/gtk/gtkbin.h
free.o: /usr/local/include/gtk/gtkcontainer.h
free.o: /usr/local/include/gtk/gtkaspectframe.h
free.o: /usr/local/include/gtk/gtkframe.h /usr/local/include/gtk/gtkarrow.h
free.o: /usr/local/include/gtk/gtkbindings.h /usr/local/include/gtk/gtkbox.h
free.o: /usr/local/include/gtk/gtkbbox.h /usr/local/include/gtk/gtkbutton.h
free.o: /usr/local/include/gtk/gtkcalendar.h
free.o: /usr/local/include/gtk/gtksignal.h
free.o: /usr/local/include/gtk/gtkmarshal.h
free.o: /usr/local/include/gtk/gtkcheckbutton.h
free.o: /usr/local/include/gtk/gtktogglebutton.h
free.o: /usr/local/include/gtk/gtkcheckmenuitem.h
free.o: /usr/local/include/gtk/gtkmenuitem.h /usr/local/include/gtk/gtkitem.h
free.o: /usr/local/include/gtk/gtkclist.h
free.o: /usr/local/include/gtk/gtkhscrollbar.h
free.o: /usr/local/include/gtk/gtkscrollbar.h
free.o: /usr/local/include/gtk/gtkrange.h
free.o: /usr/local/include/gtk/gtkvscrollbar.h
free.o: /usr/local/include/gtk/gtkcolorsel.h
free.o: /usr/local/include/gtk/gtkwindow.h /usr/local/include/gtk/gtkvbox.h
free.o: /usr/local/include/gtk/gtkpreview.h /usr/local/include/gtk/gtkentry.h
free.o: /usr/local/include/gtk/gtkeditable.h /usr/local/include/gtk/gtkhbox.h
free.o: /usr/local/include/gtk/gtkmain.h /usr/local/include/gtk/gtkscale.h
free.o: /usr/local/include/gtk/gtkhscale.h /usr/local/include/gtk/gtktable.h
free.o: /usr/local/include/gtk/gtkeventbox.h
free.o: /usr/local/include/gtk/gtkcombo.h /usr/local/include/gtk/gtkcompat.h
free.o: /usr/local/include/gtk/gtkctree.h /usr/local/include/gtk/gtkcurve.h
free.o: /usr/local/include/gtk/gtkdrawingarea.h
free.o: /usr/local/include/gtk/gtkdialog.h /usr/local/include/gtk/gtkdnd.h
free.o: /usr/local/include/gtk/gtkselection.h
free.o: /usr/local/include/gtk/gtkfeatures.h
free.o: /usr/local/include/gtk/gtkfilesel.h /usr/local/include/gtk/gtkfixed.h
free.o: /usr/local/include/gtk/gtkfontsel.h
free.o: /usr/local/include/gtk/gtknotebook.h
free.o: /usr/local/include/gtk/gtkgamma.h /usr/local/include/gtk/gtkgc.h
free.o: /usr/local/include/gtk/gtkhandlebox.h
free.o: /usr/local/include/gtk/gtkhbbox.h /usr/local/include/gtk/gtkhpaned.h
free.o: /usr/local/include/gtk/gtkpaned.h /usr/local/include/gtk/gtkhruler.h
free.o: /usr/local/include/gtk/gtkruler.h
free.o: /usr/local/include/gtk/gtkhseparator.h
free.o: /usr/local/include/gtk/gtkseparator.h
free.o: /usr/local/include/gtk/gtkimage.h
free.o: /usr/local/include/gtk/gtkinputdialog.h
free.o: /usr/local/include/gtk/gtkitemfactory.h
free.o: /usr/local/include/gtk/gtkmenufactory.h
free.o: /usr/local/include/gtk/gtklayout.h /usr/local/include/gtk/gtklist.h
free.o: /usr/local/include/gtk/gtklistitem.h /usr/local/include/gtk/gtkmenu.h
free.o: /usr/local/include/gtk/gtkmenushell.h
free.o: /usr/local/include/gtk/gtkmenubar.h
free.o: /usr/local/include/gtk/gtkoptionmenu.h
free.o: /usr/local/include/gtk/gtkpacker.h /usr/local/include/gtk/gtkpixmap.h
free.o: /usr/local/include/gtk/gtkplug.h /usr/local/include/gtk/gtkprogress.h
free.o: /usr/local/include/gtk/gtkprogressbar.h
free.o: /usr/local/include/gtk/gtkradiobutton.h
free.o: /usr/local/include/gtk/gtkradiomenuitem.h
free.o: /usr/local/include/gtk/gtkrc.h
free.o: /usr/local/include/gtk/gtkscrolledwindow.h
free.o: /usr/local/include/gtk/gtkviewport.h
free.o: /usr/local/include/gtk/gtksocket.h
free.o: /usr/local/include/gtk/gtkspinbutton.h
free.o: /usr/local/include/gtk/gtkstatusbar.h
free.o: /usr/local/include/gtk/gtktearoffmenuitem.h
free.o: /usr/local/include/gtk/gtktext.h /usr/local/include/gtk/gtkthemes.h
free.o: /usr/local/include/gtk/gtktipsquery.h
free.o: /usr/local/include/gtk/gtktoolbar.h
free.o: /usr/local/include/gtk/gtktooltips.h /usr/local/include/gtk/gtktree.h
free.o: /usr/local/include/gtk/gtktreeitem.h
free.o: /usr/local/include/gtk/gtkvbbox.h /usr/local/include/gtk/gtkvpaned.h
free.o: /usr/local/include/gtk/gtkvruler.h /usr/local/include/gtk/gtkvscale.h
free.o: /usr/local/include/gtk/gtkvseparator.h choices.h ../pixmaps/free.xpm
choices.o: config.h /usr/include/stdio.h /usr/include/sys/feature_tests.h
choices.o: /usr/include/sys/isa_defs.h /usr/include/sys/va_list.h
choices.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
choices.o: /usr/include/stdlib.h /usr/include/sys/param.h
choices.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
choices.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
choices.o: /usr/include/sys/time.h /usr/include/sys/time.h
choices.o: /usr/include/sys/unistd.h /usr/include/fcntl.h
choices.o: /usr/include/sys/fcntl.h /usr/include/errno.h
choices.o: /usr/include/sys/errno.h global.h /usr/local/include/glib.h
choices.o: /usr/local/lib/glib/include/glibconfig.h /usr/include/limits.h
choices.o: /usr/include/float.h /usr/include/stdarg.h choices.h
