#!/usr/bin/env python

import os
import sys

import findrox; findrox.version(2, 0, 3)

import rox
import rox.tasks

host='kerofin@post.demon.co.uk'

ID=0
FROM=1
TO=2
SIZE=3

class Window(rox.Window):
    def __init__(self):
        rox.Window.__init__(self)
        self.set_title(host)

        vbox=rox.g.VBox()
        self.add(vbox)

        scrw=rox.g.ScrolledWindow()
        scrw.set_size_request(256+128, 64)
        scrw.set_policy(rox.g.POLICY_NEVER, rox.g.POLICY_AUTOMATIC)
        vbox.pack_start(scrw, True, True, 2)
        
        self.store=rox.g.ListStore(int, str, str, int)
        self.view=rox.g.TreeView(self.store)

        cell=rox.g.CellRendererText()
        col=rox.g.TreeViewColumn('From', cell, text=FROM)
        self.view.append_column(col)
        
        cell=rox.g.CellRendererText()
        col=rox.g.TreeViewColumn('To', cell, text=TO)
        self.view.append_column(col)

        self.view.get_selection().set_mode(rox.g.SELECTION_NONE)

        scrw.add(self.view)

        vbox.show_all()

        self.scan=None
        rox.g.timeout_add(60*1000, self.start_update)
        self.start_update()

    def start_update(self):
        if self.scan:
            return True

        self.scan=os.popen('finger -l %s' % host)
        rox.tasks.Task(self.update())
        return True

    def update(self):
        self.store.clear()
        header_end=False
        
        while True:
            yield rox.tasks.InputBlocker(self.scan.fileno())
            line=self.scan.readline()
            if not line:
                break
            toks=line.strip().split()
            if len(toks)<4:
                continue
            if toks[0]=='---':
                header_end=True

            elif header_end:
                it=self.store.append()
                self.store.set(it, ID, int(toks[0]), FROM, toks[1],
                               TO, toks[2], SIZE, int(toks[3]))

        self.scan=None

win=Window()
win.show()

rox.mainloop()
